config/routes.rb
Rails.application.routes.draw do
  get 'user/index'
  resources :links

  resources :projects
  resources :task_list, only: [:index]

  root to: 'user#index'

end

app/models/link.rb
class Link < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_and_belongs_to_many :services
  accepts_nested_attributes_for :services, allow_destroy: true

  # validates
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: " должен указывать на логотип формата PNG, JPG или GIF."
  }
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_and_belongs_to_many :projects

  validates :name, :price, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :description, :site)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    # флаги дат, есть ли хотя бы ожна дата в таблице
    @have_start_date = false;
    @have_end_date = false;
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:id, :category, :title, :description, :image_url, :site, 
        services_attributes: [:id, :name, :price, :start_date, :end_date, :_destroy])
    end
end

app/controllers/task_list_controller.rb
class TaskListController < ApplicationController
  def index
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields fa fa-plus button middle_green", 
      data: {id: id, fields: fields.gsub("\n", "")})
  end

end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_budget.html.erb
<!--div id = "budget-menu">
  <div class="pseudo">
    <h1>Budget</h1>
    <span class = "a-project">Затраты: <em class = "right">1500р</em></span><br>
    <span class = "a-project">Доход: <em class = "right">0р</em></span><br>
    <br/>
    <span>Прибыль: <em class = "right">-1500р</em></span>
  </div>
</div>-->

app/views/layouts/_footer.html.erb
<div class="footer">
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="grid-wrap">
    <%= link_to "Den's page", "#", id: "logo" %>
  </div>
</header>

app/views/layouts/_projects.html.erb
<div id = "projects-menu">
  <div class="pseudo">
    <h1>Projects</h1>
      <% if !@projects.nil? %>
      <% @projects.each do |project| %>
        <%= link_to(project, class: "a-project") do %>
        <%= project.title %>
        <% end %>
        <%= link_to '', project, method: :delete, data: { confirm: 'Are you sure?' }, :class => "right fa fa-trash-o" %>
        <%= link_to '', edit_project_path(project), :class => "fa fa-pencil right", :style => "margin-right: 10px;" %>
        <br/>
      <% end %>
    <% end %>
    <br/>
    <%= link_to 'New Project', new_project_path %>
  </div><!--/pseudo-->
</div><!--/projects-menu-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DensPage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<ul class="cbp-vimenu">
  <li><%= link_to "Home", root_path, class: "icon-logo" %></li>
  <li><%= link_to "Projects", projects_path, class: "icon-projects" %></li>
  <li><%= link_to "Links", links_path, class: "icon-links" %></li>
  <li><%= link_to "Task list", task_list_index_path, class: "icon-book" %></li>
  <!-- Example for active item:
  <li class="cbp-vicurrent"><a href="#" class="icon-pencil">Pencil</a></li>
  -->
</ul>
<body class="<%= controller.controller_name %>">
  <%= render 'layouts/header' %>
  <section id = "grid-main">
    <div id="grid-wrap-menu" class="grid-wrap clearfix">
      <div class="pseudo">
        <div class = "pseudo2 clearfix">
        <%= yield %>
        </div><!--/pseudo2-->
      </div><!--/pseudo-->
    </div><!--/grid-main-->
  </section><!--/grid-wrap-->
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :site %><br>
    <%= f.text_field :site %>
  </div>
  <div class="actions">
    <%= f.submit :class => "button middle_green" %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Listing links</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Site</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.title %></td>
        <td><%= link.description %></td>
        <td><%= link.site %></td>

        <td><%= link_to '', edit_link_path(link), :class => "fa fa-pencil ", 
          :style => "color: #196e76;" %></td>
        <td><%= link_to '', link, method: :delete, data: { confirm: 'Are you sure?' }, :class => " fa fa-trash-o", 
          :style => "color: #196e76;" %></td> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @link.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @link.description %>
</p>

<p>
  <strong>Site:</strong>
  <%= @link.site %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="left-project">
    <div class="field">
      <%= f.label :category %><br>
      <%= f.text_field :category %>
    </div>
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :image_url %><br>
      <%= f.text_field :image_url %>
    </div>
    <div class="field">
      <%= f.label :site %><br>
      <%= f.text_field :site %><br>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
  </div><!--/left-project-->

  <div class="right-services">
    <%= render 'formServices', f: f %>
  </div><!--/right-services-->

  <%= link_to_add_fields "Add Service", f, :services %>

  <div class="actions">
    <%= f.submit :class => "button middle_green" %>
  </div>
<% end %>

app/views/projects/_formServices.html.erb
<div class = "table">
  <fieldset>
    <div class="row">
      <div class="col"><label>Service</label></div>
      <div class="col"><label>Price</label></div>
      <div class="col"><label>Start date</label></div>
      <div class="col"><label>End date</label></div>
      <div class="col remove"><label>Remove</label></div>
    </div><!--/row-->
    <%= f.fields_for :services do |builder| %>
      <div class="row">
        <div class="col"><%= builder.text_field :name %></div>
        <div class="col"><%= builder.text_field :price %></div>
        <div class="col"><%= builder.date_field :start_date %></div>
        <div class="col"><%= builder.date_field :end_date %></div>
        <div class="col remove small-in-table"><%= builder.check_box :_destroy %></div>
      </div><!--/row-->
    <% end %>
  </fieldset>
</div><!--/div-table-->

app/views/projects/_service_fields.html.erb
<div class = "table">
  <fieldset>
    <div class="row">
      <div class="col"><%= f.text_field :name %></div>
      <div class="col"><%= f.text_field :price %></div>
      <div class="col"><%= f.date_field :start_date %></div>
      <div class="col"><%= f.date_field :end_date %></div>
      <div class="col remove">
        <%= f.hidden_field :_destroy %>
        <%= link_to "", '#', class: "remove_fields fa fa-trash-o small-in-table", style: "color: #1b967e;" %>
      </div>
    </div><!--/row-->
  </fieldset>
</div><!--/div-table-->

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="left-project">
    <div class="field">
      <%= f.label :category %><br>
      <%= f.text_field :category %>
    </div>
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :image_url %><br>
      <%= f.text_field :image_url %>
    </div>
    <div class="field">
      <%= f.label :site %><br>
      <%= f.text_field :site %><br>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
  </div><!--/left-project-->

  <div class="right-services">
    <%= render 'formServices', f: f %>
    <%= link_to_add_fields "", f, :services %>
  </div><!--/right-services-->

  <div class="actions ">
    
  </div>

<ul class = "cbp-vimenu vimenu-bottom">
  <li><%= link_to 'Back', projects_path, class: "icon-back" %></li>
  <li><%= link_to 'Show', @project, class: "icon-show" %></li>
  <li><%= f.submit :class => "button middle_green margin10" %></li>
</ul>
<% end %>

app/views/projects/index.html.erb
<div id = "right-panel">
  <%= render 'layouts/projects' %>
  <%= render 'layouts/budget' %>
</div>

<div class="main-part">
  <div class="pseudo">
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.title %></td>
          <td><%= project.description %></td>
          <td><%= link_to 'Show', project %></td>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
          <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Project', new_project_path %>
  </div>
</div>

app/views/projects/new.html.erb
<div id = "right-panel">
  <%= render 'layouts/budget' %>
</div>

<div class="main-part">
<div class="pseudo">
  <h1>New project</h1>

  <%= render 'form' %>

  <%= link_to 'Back', projects_path %>
</div>
</div>

app/views/projects/show.html.erb
<h1>
  <%= @project.title %>
</h1>
<div id = "right-panel">
  <%= render 'layouts/budget' %>
  <br>
  <table>
    <thead>
      <tr>
        <td>Name</td>
        <td>Price</td>
        <td>Start date</td>
        <td>End date</td>
      </tr>
    </thead>
    <tbody>
      <% @project.services.each do |service| %>
        <tr>
          <td><%= service.name %></td>
          <td><%= service.price %></td>
          <td>
            <% if !service.start_date.nil? %>
              <%= service.start_date.strftime("%d %B %Y") %>
              <% @have_start_date = true %>
            <% end %>
          </td>
          <td>
            <% if !service.end_date.nil? %>
              <%= service.end_date.strftime("%d %B %Y") %>
              <% @have_end_date = true %>
            <% end %>
          </td>
        </tr>
      <% end %>
      <tr>
        <td>Итого: </td>
        <td><%= @project.services.sum("services.price") %></td>
        <td>
          <% if @have_start_date %>
            <%= @project.services.minimum("services.start_date").strftime("%d %B %Y") %>
          <% end %>
        </td>
        <td>
          <% if @have_end_date %>
            <%= @project.services.maximum("services.end_date").strftime("%d %B %Y") %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<div class="main-part">
<div class="pseudo">
  <% if (!@project.image_url.nil? && @project.image_url != '' )  %>
    <br>
    <p>
      <%= image_tag(@project.image_url, class: 'list_image') %>
    </p>
  <% else %>
    
  <% end %>

  <p><%= @project.description %></p>
  <br>
  
  <p>
  <% if (!@project.site.nil? && @project.site != '' )  %>
    <%= link_to("http://www."+@project.site) do %>
      <%= @project.site %>
    <% end %>
  <% end %>
  </p>

  <%= link_to 'Edit', edit_project_path(@project) %> 
  <%= link_to 'Back', projects_path %>

</div>
</div>

app/views/task_list/index.html.erb
<h1>Sticky Notes</h1>

<form>
  <select id = "note_color" class=" middle_green">
    <option value = "LightGoldenRodYellow">yellow</option>
    <option value = "PaleGreen">green</option>
    <option value = "LightPink">pink</option>
    <option value = "LightBlue">blue</option>
  </select>

  <input type = "text" id = "note_text">
  <input type = "button" id = "add_button" class = "button middle_green" value = "Add Sticky Note">
</form>

<ul id = "stickies">
</ul>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>